version: 2
updates:
    # Maintenir les dépendances Cargo
    - package-ecosystem: "cargo"
      directory: "/"
      schedule:
          interval: "weekly"
          day: "monday"
          time: "09:00"
      open-pull-requests-limit: 10
      assignees:
          - "Pierre-brtrd"
      labels:
          - "dependencies"
          - "rust"
      commit-message:
          prefix: "⬆️"
          include: "scope"

    # Maintenir les GitHub Actions
    - package-ecosystem: "github-actions"
      directory: "/"
      schedule:
          interval: "weekly"
          day: "monday"
          time: "09:00"
      assignees:
          - "Pierre-brtrd"
      labels:
          - "dependencies"
          - "github-actions"
      commit-message:
          prefix: "⬆️"
          include: "scope"
